### ISSUE TITLE
help2man error in make-ca

### ISSUE THREAD

**Issue by rushi349** [lfs-book/make-ca#26]
Hi'
 Previously I have compiled the help2man package and then going for make-ca, but it was given the following error.
ERRORS:
help2man: can't get `--help' info from ./make-ca
Try `--no-discard-stderr' if option outputs to stderr
make: *** [Makefile:13: man] Error 127

Can any one please help?

Thanks and regards!
Rushikesh J.

**Comment by pierre-labastie** [comment]
Hmm, sorry for taking so long for noticing this. For some reason, github does not send me a notification when an issue is opened on this repo...

I cannot reproduce, so not sure what your problem is. Are you using the lfs/blfs books? In any case, the supplied `Makefile` uses the help2man script provided by this package, not the system one. So this should give the same output, whether you have installed help2man before or not.

Do you still have this problem? If so, can you give us more details? building from git repo or a release? Release version if so...

**Comment by xry111** [comment]
Closing as it works for me and we've not received any feedback.
